### ISSUE TITLE
Pandas library

### ISSUE THREAD

**Issue by Satwik-uppada** [tandpfun/skill-icons#1029]
### Skill Name

Pandas

### Why?

Popular data science library

### Reference Image

![image](https://github.com/tandpfun/skill-icons/assets/92086645/4ee2ecb4-a9f3-484b-a246-e9591a314040)

**Comment by LelouchFR** [comment]
hi @Satwik-uppada if you want to use the pandas icon, you can find it on the newest version of the repository ([here](https://github.com/lelouchfr/skill-icons)), because the maintainer did not show up in months

**Comment by tandpfun** [comment]
@LelouchFR I believe I've mentioned this to you before, but please do not link to your project on this repo at all from now on, and definitely not on every single issue here that is created. It creates a lot of spam and is arguably self-promotion. Your repo is not "the newest version of the project", it's a fork that is maintained. While I see where you're coming from and can understand from a positive side why you are doing this, you're breaking GitHub's Community Guidelines in the ways in which you are doing it. Comments on issues/PRs should be productive and relevant to this repo only.

Because of these reasons, I'm issuing a block of your account from this repo. I'm really glad you've helped keep it maintained, but I do not appreciate your borderline unfeeling/unkind comments and assumptions towards me without knowing anything about my personal situation. Best of luck from here on!

**Comment by Satwik-uppada** [comment]
Sorry for the inconvenience from my side, i just used it for my profile
readme. That's it
